services:
  api:
    image: ghcr.io/daddatejja/aichatbox-api:latest
    container_name: aichatbox-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - Jwt__Key=${JWT_KEY}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - Gemini__ApiKey=${GEMINI_API_KEY}
      - ConnectionStrings__DefaultConnection=Host=db;Database=aichatbox;Username=admin;Password=${DB_PASSWORD}
      - DashboardUrl=https://appchatbox.daddatejja.dev/login
      - Network__PublicApiUrl=${PUBLIC_API_URL}
    networks:
      - chat-network

  db:
    image: postgres:16-alpine
    container_name: aichatbox-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=aichatbox
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aichatbox"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

  dashboard:
    image: ghcr.io/daddatejja/aichatbox-dashboard:latest
    container_name: aichatbox-dashboard
    restart: always
    networks:
      - chat-network

  caddy:
    image: caddy:latest
    container_name: aichatbox-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - api
      - dashboard
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
