@AiChatBox.Api_HostAddress = http://localhost:5180

GET {{AiChatBox.Api_HostAddress}}/api/chat/sessions
Accept: application/json

###
POST {{AiChatBox.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{ "email": "test@test.com", "password": "test123" }

###
